name: Déployer des fichiers statiques vers GitHub Pages

env:
  ACTIONS_STEP_DEBUG: true

on: push
#  # Les branches pour lesquelles déclencher ce workflow
#  push:
#    branches: ["main"]

# Permissions du GITHUB_TOKEN pour permettre le déploiement GitHub Pages (autogénéré)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    # Image Ubuntu
    # La version doit être mise à jour pour tenir compte du
    # cycle de vie des distributions d’Ubuntu. Il est possible
    # que GitHub déprécie une version et qu’elle ne soit plus
    # supportée sur le service GitHub Actions; si aucun runner
    # ne prend la tâche, c’est possiblement pour cette raison.
    #
    # Ubuntu Release Cycle:
    # https://ubuntu.com/about/release-cycle
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # Ici, nous utilisons 'latest', la version utilisée peut
      # être différente de la vôtre. Vous pouvez spécifier une
      # version en particulier:
      # ex. docker://pandoc/core:2.9
      #
      # Docker image list (Pandoc):
      # https://hub.docker.com/r/pandoc/core/tags
      - uses: docker://pandoc/core:latest

      - name: Construire le site
        id: build
        run: bash site/site.sh

#      - uses: actions/upload-artifact@v3
#        name: Téléverser les artefacts
#        id: upload
#        with:
#          # name -> pour la prochaine étape
#          name: site
#          path: ./site

  deploy:

    # Add a dependency to the build job
    needs: build

    permissions:
      contents: write

    # idem (voir bloc plus haut)
    runs-on: ubuntu-22.04

    steps:
      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
